### ISSUE TITLE
Please choose a license

### ISSUE THREAD

**Issue by jbyler** [richardlawley/server-switcher#1]
GitHub [has provided](https://github.com/blog/1530-choosing-an-open-source-license) a site called [choosealicense.com](http://choosealicense.com) to make it easy to open source your project.  I'd like to request that you choose a license and include it with your source code.

Keep in mind that not choosing a license means you default to [all rights reserved](http://choosealicense.com/no-license/), which means no one may fork or modify this project.  If that's your intent, that's OK too, but would you mind being explicit about it to avoid confusion?

Thanks!

**Comment by richardlawley** [comment]
Marked as MIT.

**Comment by jbyler** [comment]
Thanks Richard!
